apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc1
  template:
    metadata:
      labels:
        app: poc1
    spec:
      containers:
        - name: poc1
          image: "wunderpark/poc1"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: poc1
spec:
  selector:
    app: poc1
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
